# Generated by Django 4.0.5 on 2022-07-15 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, null=True)),
                ('emp_code', models.IntegerField(null=True)),
                ('mobile', models.CharField(max_length=200, null=True)),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_register.position')),
            ],
        ),
    ]
